### ISSUE TITLE
Consistency testset for Docrepair model?

### ISSUE THREAD

**Issue by Archonsh** [lena-voita/good-translation-wrong-in-context#5]
Dear Authors,

I am trying to evaluate a Docrepair model trained with your emnlp2019 data. However, I didn't find the consistency testset for the Docrepair model. The /consistency_testsets/scoring_data is from English to Russian.

Could you please hint on how to get the consistency score for the Docrepair model?

**Comment by lena-voita** [comment]
Dear Archonsh,

That is right - the test set is from English to Russian: since the final task is translation, test set is also for the task (not for the model).

When using DocRepair, your pipeline is the following:
1) base (context-agnostic) model generates translations of sentences,
2) these translations are fed to DocRepair,
3) the resulting DocRepair translations (or scores) are evaluated.

For this, you have to use English-Russian test sets provided in our repo.
